[build]
builder = "DOCKERFILE"
dockerfilePath = "railway-hybrid-prod.Dockerfile"

[deploy]
startCommand = "node h.js"
healthcheckPath = "/ping"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments]
  [environments.production]
    startCommand = "node h.js"