[build]
buildCommand = ""
startCommand = "sh start.sh"
dockerfilePath = "Dockerfile.railway"
nixpacksPlan.phases.setup.nixPkgs = ["nodejs_20"]

[deploy]
healthcheckPath = "/ping"
healthcheckTimeout = 60000
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[resources]
memoryLimit = 512
cpuLimit = 0.5