[build]
buildCommand = ""
startCommand = "node server/src/index.js"
dockerfilePath = "Dockerfile.production"

[deploy]
healthcheckPath = "/ping"
healthcheckTimeout = 10000
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[resources]
memoryLimit = 512
cpuLimit = 0.5